### ISSUE TITLE
RI-001: Información sobre los usuarios.

### ISSUE THREAD

**Issue by marpercor8** [marpercor8/BookStorePGPI-G1.4#19]
El sistema debe de poder almacenar los datos correspondientes en la creación de un usuario 
(nombre, apellidos, correo, fecha nacimiento, NIF, si tiene privilegios de administrador y 
contraseña).

RN-001: No podrá haber más de un usuario con el mismo NIF.
RN-004: No se podrá eliminar una cuenta de un usuario que ha realizado un pedido el cual se encuentra en pendiente, para evitar fallos en el sistema.

**Comment by cargarrod12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PGPI-G14-6370c1db6227caa44cd5f745/issues/marpercor8/BookStorePGPI-G1.4/19?planning-poker) with Zenhub @ramoonrb @marrodgar62 @marpercor8 @alvuberui
