### ISSUE TITLE
RI-002: Informacion sobre los libros

### ISSUE THREAD

**Issue by marpercor8** [marpercor8/BookStorePGPI-G1.4#21]
El sistema debe de poder almacenar los datos correspondientes de los libros (nombre, 
editorial, categoría, precio, unidades, autor, imagen).

**Comment by cargarrod12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PGPI-G14-6370c1db6227caa44cd5f745/issues/marpercor8/BookStorePGPI-G1.4/21?planning-poker) with Zenhub @alvuberui @marrodgar62 @marpercor8 @ramoonrb
