### ISSUE TITLE
RI-004: Información sobre los pedidos.

### ISSUE THREAD

**Issue by marpercor8** [marpercor8/BookStorePGPI-G1.4#23]
El sistema debe de poder almacenar los datos correspondientes de las compras (usuario, 
libros, dirección, localidad, provincia, código postal, hora, envío, precio).

**Comment by cargarrod12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PGPI-G14-6370c1db6227caa44cd5f745/issues/marpercor8/BookStorePGPI-G1.4/23?planning-poker) with Zenhub @ramoonrb @marrodgar62 @marpercor8 @alvuberui
