### ISSUE TITLE
RF-002: Modificación de datos de usuario

### ISSUE THREAD

**Issue by marpercor8** [marpercor8/BookStorePGPI-G1.4#33]

**Comment by cargarrod12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PGPI-G14-6370c1db6227caa44cd5f745/issues/marpercor8/BookStorePGPI-G1.4/33?planning-poker) with Zenhub @ramoonrb @marrodgar62 @marpercor8 @alvuberui
