### ISSUE TITLE
RF-002: Modicación de datos de usuario

### ISSUE THREAD

**Issue by marpercor8** [marpercor8/BookStorePGPI-G1.4#35]

**Comment by cargarrod12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PGPI-G14-6370c1db6227caa44cd5f745/issues/marpercor8/BookStorePGPI-G1.4/35?planning-poker) with Zenhub @alvuberui @marpercor8 @marrodgar62 @ramoonrb
